### ISSUE TITLE
Cannot build electron app with bundleApp 

### ISSUE THREAD

**Issue by bmalkow** [rjaros/kvision#150]
When I try to build my project I saw error. The same error I see when I try to build `template-electron`:
```
> Task :bundleApp FAILED
  • electron-builder  version=21.2.0 os=19.4.0
  • loaded configuration  file=/Users/bmalkow/tmp/kvision-examples/template-electron/build/dist/electron-builder.yml
  • author is missed in the package.json  appPackageFile=/Users/bmalkow/tmp/kvision-examples/template-electron/build/dist/package.json
  • installing production dependencies  platform=darwin arch=x64 appDir=/Users/bmalkow/tmp/kvision-examples/template-electron/build/dist
  ⨯ spawn npm ENOENT  stackTrace=
                        Error: spawn npm ENOENT
                            at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
                            at onErrorNT (internal/child_process.js:456:16)
                            at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by rjaros** [comment]
The `template-electron` project works fine for me on Linux. You are trying to build on MacOS, right? Do you have `npm` installed on your system?

**Comment by bmalkow** [comment]
Damn! I forgot to install it after system installation.
Error message wasn't helpful in it ;-)

Sorry for troubles.
