### ISSUE TITLE
ClassCastException error in browser log

### ISSUE THREAD

**Issue by kam1sh** [rjaros/kvision#265]
Hi! I've got next issue after upgrading a lot of dependencies in my personal project:
```
"ClassCastException: Illegal cast
    at Object.captureStack (webpack-internal:///./kotlin-dce-dev/kotlin.js:39116:15)
    at ClassCastException.Exception [as constructor] (webpack-internal:///./kotlin-dce-dev/kotlin.js:39449:14)
    at ClassCastException.RuntimeException [as constructor] (webpack-internal:///./kotlin-dce-dev/kotlin.js:39475:17)
    at RuntimeException_init_0 (webpack-internal:///./kotlin-dce-dev/kotlin.js:39486:24)
    at new ClassCastException (webpack-internal:///./kotlin-dce-dev/kotlin.js:39605:7)
    at throwCCE_0 (webpack-internal:///./kotlin-dce-dev/kotlin.js:43121:13)
    at eval (webpack-internal:///./kotlin-dce-dev/cec-platform-frontend.js:14700:164)
    at Object.eval [as insert] (webpack-internal:///./kotlin-dce-dev/kvision-jsLegacy.js:7801:11)
    at KVManager.patch [as sdPatch_0] (webpack-internal:///../../node_modules/snabbdom/es/snabbdom.js:311:45)
    at KVManager.patch_aevwwv$ (webpack-internal:///./kotlin-dce-dev/kvision-jsLegacy.js:538:17)"
```

Also there is a another huge stack trace (because of coroutines usage), there are also frames with Ktor HTTP Client, so I'm not sure this is issue with KVision. Here are some parts of stacktrace:
![image](https://user-images.githubusercontent.com/14600211/117570882-e535dd80-b0d4-11eb-974e-3a47db5c543a.png)
![image](https://user-images.githubusercontent.com/14600211/117570903-f848ad80-b0d4-11eb-8915-c519fadea0bd.png)

I tried downgrading KVision, Ktor, etc, but the error persists. Can you help me with that?

_Thank you._
_Igor_

**Comment by GrishinSergeyLexpharma** [comment]
Привет! Для начала настрой браузер так, чтобы он показывал исходники *.kt

Note: Source maps are disabled by default in all KVision template projects, because the development cycle (hot reload) is a lot faster without them. To enable source maps you need to remove line sourceMaps = false from your build.gradle.kts file and remove line config.devtool = 'eval-cheap-source-map' from webpack.config.d/webpack.js file.

**Comment by rjaros** [comment]
Hi,

From your stacktrace I see you have `Page` class in your project? Is this your own class or is it `io.kvision.onsenui.core.Page`? Do you override `dispose()` method in this class?

**Comment by kam1sh** [comment]
@GrishinSergeyLexpharma Enabled source maps now, but I see only my source code in Kotlin, KVision is in JavaScript:
![image](https://user-images.githubusercontent.com/14600211/117578945-7f0f8180-b0f9-11eb-9d2b-a343aadd378c.png)

@rjaros `Page` is my own class, yes. 

Right now I'm using Chrome debugger and trying to find the place where the exception throws. I'll tell you all if I find anything.
