### ISSUE TITLE
ClassCastException when taking Intellij's advice on casting event to Unit

### ISSUE THREAD

**Issue by reubenfirmin** [rjaros/kvision#417]
This happens when showing a custom context menu. 

```ClassCastException
    at THROW_CCE (webpack-internal:///./kotlin/kotlin-kotlin-stdlib-js-ir.js:19120:11)
    at Object.eval (webpack-internal:///./kotlin/hacks-ink.js:4882:9)
    at invokeHandler (webpack-internal:///../../node_modules/snabbdom/build/modules/eventlisteners.js:8:17)
    at handleEvent (webpack-internal:///../../node_modules/snabbdom/build/modules/eventlisteners.js:22:9)
    at HTMLDivElement.handler (webpack-internal:///../../node_modules/snabbdom/build/modules/eventlisteners.js:27:9)```

```

```
fun attachMouseBehavior(tag: Tag) {
        tag.onEvent {
            contextmenu = { event ->
                event.stopPropagation()
                event.preventDefault() as Unit
            }

            mousedown = { event ->
                if (event.button.toInt() == 2) {
                    println("a")
                    showContextMenu(event, event.clientX, event.clientY)
                    event.stopPropagation()
                    event.preventDefault()
                    println("b")
                }
            }
        }
    }
```

Both "a" and "b" are printed in the console, so it's not clear what additional code runs to cause this. It doesn't seem to impede functionality.

**Comment by reubenfirmin** [comment]
![2022-07-04_07-08](https://user-images.githubusercontent.com/14217993/177161364-8b783655-eb99-4c03-b99b-038a694c5c92.png)

**Comment by rjaros** [comment]
This is an exception from your explicit `as Unit` casting. It was probably suggested by the IDE, but it's wrong. Use one of these to avoid IDE warnings and runtime errors:
```
            @Suppress("UnsafeCastFromDynamic")
            event.preventDefault()
```

```
            event.preventDefault().unsafeCast()        
```

```
            event.preventDefault()
            Unit
```

**Comment by reubenfirmin** [comment]
I overlooked the contextMenu event. My bad. Thanks
