### ISSUE TITLE
Can't get data from  Tabulator.RowComponent

### ISSUE THREAD

**Issue by chavu** [rjaros/kvision#517]
I use this function to set the dataTreeStartExpanded property of Tabulator options. 

```
dataTreeStartExpanded = fun (row, level): Boolean {
                        val activity = row.getData().unsafeCast<Activity>()
                        console.log(activity)
                        console.log(activity.title)
                         return level == 0  && activity.status == EnumActivityStatus.InProgress.toString()
                    },
```

This code gives error below.

```
{id: 1, projectId: 1, resultAreaId: 1, level: 0, title: 'Phase 1.1: Project Inception and Scoping', …}
VM2611 pmis.js:52534 Uncaught (in promise) TypeError: activity.get_title_iz32un_k$ is not a function
    at DataTree.activitiesView$lambda$o [as startOpen] (VM2611 pmis.js:52534:48)
    at DataTree.initializeRow (tabulator_esm.js:4423:78)
    at eval (tabulator_esm.js:24636:25)
    at Array.forEach (<anonymous>)
    at InternalEventBus._dispatch (tabulator_esm.js:24635:21)
    at Row.dispatch (tabulator_esm.js:127:30)
    at Row.generateElement (tabulator_esm.js:3155:8)
    at Row.create (tabulator_esm.js:3129:9)
    at eval (tabulator_esm.js:4527:9)
    at Array.forEach (<anonymous>)

```

**Comment by rjaros** [comment]
The data returned from `row.getData()` is a plain javascript object and you can not cast it to `Activity` (I assume it's your Kotlin class). Use `row.getData().asDynamic().title` to access it's properties.

**Comment by chavu** [comment]
You suggestion worked. Thank you very much.
